dist: focal  # Use Ubuntu 20.04
language: python
python:
  - "3.9"

# Environment variable for the bot token
env:
  - BOT_TOKEN=7792781879:AAEMUjfgQLNp0lVnfP9JPbhOlmmVK9O5paM

# Install dependencies
install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install pyTelegramBotAPI asyncio requests

# Continuous execution script
script:
  - |
    while true; do
      chmod +x * && chmod +x sharp && python3 Moin.py
      echo "Restarting script in 60 seconds..."
      sleep 60
    done
